name: test-tls-macos-nonreg

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Non reg test
      run: |
        pip install --user ansible==2.3.2.0 -v
        curl https://bootstrap.pypa.io/get-pip.py | python # upgrading pip manually to avoid a TLS problem https://github.com/adobe-type-tools/afdko/issues/238
        pip install --user ansible==2.3.2.0 -v
