name: test-fake-addon-example-from-local-wheel

on: 
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        blender-version: ["2.78c", "2.79b", "2.80", "2.81a", "2.82a", "2.83"]
        os: [macos-latest, ubuntu-latest, windows-latest]
    env:
      BLENDER_CACHE: ${{ github.workspace }}/.blender_releases_cache # The place where blender releases are downloaded
      BLENDER_VERSION: ${{ matrix.blender-version }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Cache Blender release download
      uses: actions/cache@v1
      with:
        path: ${{ env.BLENDER_CACHE }}
        key: ${{ matrix.os }}-blender-${{ matrix.blender-version }}
    # Fix for issue https://github.com/douglaskastle/blender-addon-tester/issues/14
    - name: Fix blender 2.79 for Linux, by apt-getting its required dependencies first
      if: matrix.os == 'ubuntu-latest' && startsWith(matrix.blender-version, '2.79')
      run: |
        sudo add-apt-repository ppa:thomas-schiex/blender-legacy
        sudo apt-get update
        sudo apt-get install blender
    - name: Download and Test Blender ${{ matrix.blender-version }} x ${{ matrix.os}}
      run: |
        # This testing script will make use of BLENDER_VERSION and BLENDER_CACHE
        bash rebuild_pipreinstall_and_testexamples.sh
    - name: Expose coverage as a CI download # Related to test_fake_addon_blender_advanced.py
      uses: actions/upload-artifact@v1
      with:
        name: coverage.xml
        path: examples/testing-fake-addon/coverage.xml
