name: test-fake-addon-example-from-local-wheel

on: 
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        blender-version: ["2.78c", "2.79b", "2.80", "2.81a", "2.82a", "2.83"]
        os: [ubuntu-latest, windows-latest]
    env:
      BLENDER_CACHE: ${{ github.workspace }}/.blender_releases_cache # The place where blender releases are downloaded

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Cache Blender release download
      uses: actions/cache@v1
      with:
        path: ${{ env.BLENDER_CACHE }}
        key: ${{ matrix.os }}-blender-${{ matrix.blender-version }}
    - name: Download and Test Blender ${{ matrix.blender-version }} x ${{ matrix.os}}
      run: |
        bash rebuild_pipreinstall_and_testexamples.sh
        cd examples/testing-fake-addon/
        # These scripts will detect and use the BLENDER_CACHE environment variable
        python test_addon_blender.py ${{ matrix.blender-version }} fake_addon && python test_fake_addon_blender_advanced.py ${{ matrix.blender-version }} && python test_fake_addon_blender_prezipped_addon.py ${{ matrix.blender-version }}
    - name: Expose coverage as a CI download # Related to test_fake_addon_blender_advanced.py
      uses: actions/upload-artifact@v1
      with:
        name: coverage.xml
        path: examples/testing-fake-addon/coverage.xml
